server:
#  port: ${TODO_PORT_NUM}
  port: 8080

spring:
  profiles:
    include: API-KEY

  datasource:
#    mariadb
#    driverClassName: org.mariadb.jdbc.Driver
#
#    url: jdbc:mysql://${TODO_MYSQL_HOST}:${TODO_MYSQL_PORT}/${TODO_DATA_BASE_NAME}?serverTimezone=Asia/Seoul
#    username: ${TODO_MYSQL_USER_NAME}
#    password: ${TODO_MYSQL_PASSWORD}
#    url: jdbc:mariadb://localhost:3306/database
#    url: jdbc:mariadb://svc.sel4.cloudtype.app:30014/test?serverTimezone=Asia/Seoul
#    username: root
#    password: tkdrnr13@

#    oracle
#    driverClassName: oracle.jdbc.OracleDriver

#    mysql
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Seoul
#    username: admin
#    password: admin
    url: jdbc:mysql://34.64.45.3:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: tkdrnr13@


#    url: jdbc:mysql://${TODO_MYSQL_HOST}:${TODO_MYSQL_PORT}/${TODO_DATA_BASE_NAME}?serverTimezone=Asia/Seoul
#    username: ${TODO_MYSQL_USER_NAME}
#    password: ${TODO_MYSQL_PASSWORD}




  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate:
    #      ddl-auto: update
          ddl-auto: create

# jwt.secret.key의 값은 256bit 이상이어야 합니다.
#jwt:
#  secret:
#    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M

openai:
  api-key: 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

chatgpt:
  api-key: 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